"""Backward-compatible pipeline exports."""

from visioncloak.pipeline import (  # noqa: F401
    DISPLAY_MAX,
    DISPLAY_MIN,
    MAX_INPUT_DIMENSION,
    MIN_CROP_DIMENSION,
    DetectedFace,
    ImageTypeResult,
    VerificationResult,
    _prepare_face_batch,
    amplified_diff_image,
    classify_image_type,
    cosine_similarity,
    detect_image_type,
    detect_primary_face,
    ensure_rgb,
    extract_clip_embedding_numpy,
    extract_clip_embedding_tensor,
    extract_embedding_numpy,
    extract_embedding_tensor,
    interpret_clip_score,
    interpret_score,
    normalize_clip_pixel_values,
    perturbation_preview_image,
    resize_for_detection,
    standardized_tensor_to_pil,
    verify_cloak,
)

